import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { AuthCheck } from "@/components/auth-check";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-nunito-sans antialiased min-h-screen flex bg-beige-light flex-col gap-8`}
      >
        <AuthCheck>
          <>
            <Header />
            {children}
            <Footer />
          </>
        </AuthCheck>
      </body>
    </html>
  );
}
