import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-nunito-sans antialiased min-h-screen flex bg-beige-light flex-col gap-8`}
      >
        <>
          {children}
          <Toaster />
        </>
      </body>
    </html>
  );
}
